<a href="https://colab.research.google.com/github/suryansh24-coder/Machine-Learning-Journey/blob/main/Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df = pd.read_csv('covid_toy.csv')

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train , y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'] , test_size = 0.2 , random_state=42)

In [12]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [15]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [16]:
# Ordinalencoding
oe =  OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [18]:
ohe = OneHotEncoder(drop='first' , sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [19]:
# Extracting Age :-
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [21]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough), axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)
X_train_transformed.shape

(80, 7)

In [22]:
X_train_transformed

array([[ 81., 101.,   0.,   0.,   0.,   1.,   0.],
       [  5., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 73., 103.,   0.,   1.,   0.,   0.,   0.],
       [ 70., 103.,   1.,   0.,   1.,   0.,   1.],
       [ 49., 102.,   0.,   1.,   0.,   0.,   0.],
       [ 51., 101.,   0.,   0.,   1.,   0.,   1.],
       [ 64., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 83., 101.,   0.,   0.,   1.,   0.,   0.],
       [ 65.,  98.,   0.,   0.,   0.,   1.,   0.],
       [ 18., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 103.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 84., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 51., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 69., 102.,   0.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 69., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 44., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 74., 102.,   1.,   0.,   0.,   1.,   0.],
       [ 20., 101.,   0.,   0.,   0.,   1.,   1.],
       [ 12., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 33., 102.,   0.,   1.,   0.,   0.,   1.],
       [ 42., 101.,   0.,   0.,   0.,   0.,   1.],
       [ 65.,  99.,   1.,   1.,   0.,   0.,   0.],
       [ 23., 101.,   1.,   0.,   0.,   1.,   0.],
       [ 56., 104.,   0.,   0.,   0.,   0.,   1.],
       [ 64., 102.,   1.,   0.,   0.,   0.,   0.],
       [ 13., 100.,   0.,   0.,   1.,   0.,   1.],
       [ 31.,  98.,   0.,   0.,   1.,   0.,   0.],
       [ 40.,  98.,   0.,   1.,   0.,   0.,   1.],
       [ 49., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 11., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 14., 101.,   1.,   0.,   0.,   0.,   1.],
       [ 42., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 38., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 46., 103.,   1.,   0.,   0.,   0.,   1.],
       [ 71., 101.,   1.,   0.,   1.,   0.,   1.],
       [ 10.,  98.,   0.,   0.,   1.,   0.,   1.],
       [ 60.,  99.,   0.,   0.,   0.,   1.,   0.],
       [ 22.,  99.,   0.,   0.,   0.,   0.,   0.],
       [ 19., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 65.,  99.,   1.,   0.,   0.,   0.,   0.],
       [ 19., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 54., 104.,   0.,   0.,   1.,   0.,   1.],
       [ 81.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 20., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 48., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 82., 101.,   1.,   0.,   1.,   0.,   0.],
       [ 23.,  98.,   1.,   0.,   0.,   1.,   1.],
       [ 66.,  99.,   1.,   0.,   0.,   0.,   1.],
       [  5.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 49.,  99.,   0.,   0.,   0.,   0.,   1.],
       [  5., 102.,   1.,   0.,   1.,   0.,   0.],
       [ 34., 101.,   0.,   1.,   0.,   0.,   1.],
       [ 79., 101.,   1.,   0.,   1.,   0.,   1.],
       [  6., 104.,   0.,   0.,   1.,   0.,   0.],
       [ 10., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 69.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 55., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 34., 101.,   0.,   0.,   0.,   1.,   1.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 47., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 73.,  98.,   1.,   0.,   0.,   0.,   0.],
       [ 42., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 80.,  98.,   0.,   1.,   0.,   0.,   0.],
       [ 47., 101.,   1.,   0.,   0.,   0.,   1.],
       [ 38., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 34., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 25., 104.,   1.,   0.,   0.,   0.,   0.],
       [ 24.,  98.,   1.,   0.,   1.,   0.,   0.],
       [ 12.,  98.,   1.,   0.,   0.,   0.,   1.],
       [ 24., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 75., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 51., 104.,   1.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   1.,   0.,   1.],
       [ 11., 100.,   0.,   0.,   1.,   0.,   1.]])

In [23]:
# Now solving this problem with the Column transformation :-
from sklearn.compose import ColumnTransformer

In [28]:
transformer = ColumnTransformer(transformers=
 [('tnf1', SimpleImputer(),['fever']),
  ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
  ('tnf3', OneHotEncoder(sparse_output=False , drop='first'),['gender','city'])],
  remainder='passthrough')

In [29]:
transformer.fit_transform(X_train).shape

(80, 7)

In [30]:
transformer.fit_transform(X_test).shape

(20, 7)