In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [17]:
data ={
    "SquareFootage" : [1500,2000,1200,1800,1350] ,
    "Bedrooms" : [3,4,2,3,3],
    "Bathrooms" : [2,2.5,1.5,2,2] ,
    "Location" : ['Suburb' ,'City','Rural','City','Suburb'] ,
    "Prices" : [250000,300000,180000,280000,220000]
    }

In [18]:
df = pd.DataFrame(data)

In [19]:
df

   SquareFootage  Bedrooms  Bathrooms Location  Prices
0           1500         3        2.0   Suburb  250000
1           2000         4        2.5     City  300000
2           1200         2        1.5    Rural  180000
3           1800         3        2.0     City  280000
4           1350         3        2.0   Suburb  220000

In [20]:
# converting location into column to dummy
df = pd.get_dummies(df , columns=['Location'])

In [21]:
df

,SquareFootage,Bedrooms,Bathrooms,Prices,Location_City,Location_Rural,Location_Suburb
0,1500,3,2.0,250000,False,False,True
1,2000,4,2.5,300000,True,False,False
2,1200,2,1.5,180000,False,True,False
3,1800,3,2.0,280000,True,False,False
4,1350,3,2.0,220000,False,False,True

In [22]:
# Feature extraction
X = df.drop('Prices' , axis =1)
y = df['Prices']

In [23]:
X_train, X_test , y_train ,y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [24]:
model = GradientBoostingRegressor()
model.fit(X_train , y_train)

GradientBoostingRegressor()

In [25]:
y_pred = model.predict(X_test)

In [26]:
mse = mean_squared_error(y_test , y_pred)

In [27]:
print(mse)

400050468.2496885

In [30]:
# User Input
print("Enter the details for house prediction : \n ")
sq_footage =  float(input("SqareFootage : "))
bedrooms = int(input("Bedrooms : "))
bathrooms = float(input("Bathrooms : "))
Location = input("Location (Suburb/City/Rural): ")
input_location = [0,0,0]
if Location[0] == 'Suburb':
  input_location[0] = 1
elif Location[0] == 'City':
  input_location[1] = 1
elif Location[0] == 'Rural':
  input_location[2] = 1
else:
  exit

user_input = pd.DataFrame({
    'SquareFootage' : [sq_footage],
    'Bedrooms' : [bedrooms],
    'Bathrooms' : [bathrooms],
    'Location_City' : [input_location[1]] ,
    'Location_Rural' : [input_location[2]] ,
    'Location_Suburb' : [input_location[0]]
})


Predcited_Price = model.predict(user_input)
print(f"Predicted Price for the house : {Predcited_Price[0]}")

Enter the details for house prediction :

SqareFootage : 1500
Bedrooms : 5
Bathrooms : 3.5
Location (Suburb/City/Rural): Rural
Predicted Price for the house : 257864.27495941045